baseURL = "https://arslankhanali.github.io/my-blog/"
languageCode = 'en-us'
title = 'AK Blogs'
theme = 'rusty-typewriter'

# For github pages
[caches]
  [caches.images]
    dir = ':cacheDir/images'

themesdir = '../..'
enableRobotsTXT = true

##########################
# RUSTY THEME VARIABLES
##########################
[params.rtwt]
  sidePane = true
  countPageItems = 30

[params.rtwt.home]
  showBio = true
  showAuthorImg = true
  sidePaneTags = true
  showFeatured = true
  showRecent = true
  hideRecentWhenFeatured = true
  countRecent = 5

[params.rtwt.side.home]
  sidePaneSticky = false
  taxonomies = ['tags','series','topics']
  countTaxonomy = 5

[params.rtwt.side.single]
  sidePaneSticky = true
  showDetails = true
  showTableOfContents = true
  showAttachments = true
  showRelated = true
  countRelated = 5
##########################

[taxonomies]
tag = 'tags'
topic = 'topics'
series = 'series'

[params.author]
name = 'Arslan'

##########################
# Main menu items
##########################
[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 1

[[menus.main]]
name = 'Gallery'
pageRef = '/gallery'
weight = 2

[[menus.main]]
name = 'About'
pageRef = '/about.md'
weight = 3
##########################

# build search index ================
[outputFormats]
 [outputFormats.SearchIndex]
  mediaType = "application/json"
  baseName = "searchindex"
  isPlainText = true
  notAlternative = true

[mediaTypes]
 [mediaTypes."application/json"]
  suffixes = ["json"]

[outputs]
 home = ["HTML","RSS", "SearchIndex"]
# ===================================

##########################
[security]
  enableInlineShortcodes = true

enableEmoji = true

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
    [markup.goldmark.renderer]
      unsafe = true

########################## Adding Buttons for edit and copy
[params]
  customCSS = ["css/custom.css"]